# Generated by Django 4.0.5 on 2022-08-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.BooleanField(),
        ),
    ]
