# Generated by Django 4.0.5 on 2022-08-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_image_alter_reply_image_alter_user_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.BooleanField(default=False),
        ),
    ]
