# Generated by Django 4.0.5 on 2022-09-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_notification_recipientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='creatorHasPicture',
        ),
        migrations.RemoveField(
            model_name='post',
            name='userHasPicture',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='userHasPicture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hasBanner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hasPicture',
        ),
        migrations.AddField(
            model_name='notification',
            name='creatorPictureID',
            field=models.CharField(default=1664255866727, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='userPictureID',
            field=models.CharField(default=1664255866727, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='userPictureID',
            field=models.CharField(default=1664255866727, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bannerID',
            field=models.CharField(default=1664255866727, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pictureID',
            field=models.CharField(default=1664255866727, max_length=255),
            preserve_default=False,
        ),
    ]
