# Generated by Django 4.0.5 on 2022-06-21 20:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=255)),
                ('banner', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=200)),
                ('following', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('followers', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
