# Generated by Django 4.0.5 on 2022-08-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_created_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='target',
            new_name='target_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='creator_name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target_name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
