# Generated by Django 4.0.5 on 2022-08-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_creator_notification_creator_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target_name',
        ),
    ]
