# Generated by Django 4.0.5 on 2022-09-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='username',
            field=models.CharField(default='hydroxide', max_length=200),
            preserve_default=False,
        ),
    ]
