# Generated by Django 4.0.5 on 2022-09-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_reply_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userPicture',
            field=models.BooleanField(default=False),
        ),
    ]
