# Generated by Django 4.0.5 on 2022-09-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_reply_userpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='creator_picture',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
