# Generated by Django 4.0.5 on 2022-09-22 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_notification_creator_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='creator_picture',
            new_name='creatorHasPicture',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='creator_id',
            new_name='creatorID',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='creator_name',
            new_name='creatorUsername',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='target_id',
            new_name='recipientID',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userPicture',
            new_name='userHasPicture',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='userPicture',
            new_name='userHasPicture',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='banner',
            new_name='hasBanner',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='hasPicture',
        ),
    ]
