# Generated by Django 4.0.5 on 2022-09-22 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_creator_picture_notification_creatorhaspicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
